// catalog.js — catálogo de juegos a comparar.
// steamId: appid de Steam (la API de Steam es la única que usa IDs).
//   ⚠️ TODOS los appids fueron verificados contra store.steampowered.com/api/appdetails
//   (los que apuntaban a otro juego fueron corregidos o descartados).
// genre: género principal (usado por el filtro de búsqueda de la página de ofertas).
// msTerm / epicTerm: términos de búsqueda por defecto (opcional, se usa el nombre si no está).
'use strict';

const GAMES = [
  // — Xbox / Microsoft Store first-party (muy presentes en MS Store) —
  { name: 'Forza Horizon 5', steamId: 1551360, genre: 'Carreras' },
  { name: 'Forza Horizon 4', steamId: 1293830, genre: 'Carreras' },
  { name: 'Forza Motorsport', steamId: 2440510, genre: 'Carreras' },
  { name: 'Halo: The Master Chief Collection', steamId: 976730, genre: 'Shooter' },
  { name: 'Halo Infinite', steamId: 1240440, genre: 'Shooter' },
  { name: 'Sea of Thieves', steamId: 1172620, genre: 'Aventura' },
  { name: 'Age of Empires IV', steamId: 1466860, genre: 'Estrategia' },
  { name: 'Age of Empires II: Definitive Edition', steamId: 813780, genre: 'Estrategia' },
  { name: 'Age of Empires III: Definitive Edition', steamId: 933110, genre: 'Estrategia' },
  { name: 'Age of Mythology: Retold', steamId: 1934680, genre: 'Estrategia' },
  { name: 'Gears 5', steamId: 1097840, genre: 'Shooter' },
  { name: 'Gears Tactics', steamId: 1184050, genre: 'Estrategia' },
  { name: 'Grounded', steamId: 962130, genre: 'Supervivencia' },
  { name: 'Pentiment', steamId: 1205520, genre: 'Aventura' },
  { name: 'Hi-Fi RUSH', steamId: 1817230, genre: 'Acción' },
  { name: 'Psychonauts 2', steamId: 607080, genre: 'Plataformas' },
  { name: 'Psychonauts', steamId: 3830, genre: 'Plataformas' },
  { name: 'Deathloop', steamId: 1252330, genre: 'Shooter' },
  { name: 'Ghostwire: Tokyo', steamId: 1475810, genre: 'Acción' },
  { name: 'Redfall', steamId: 1294810, genre: 'Shooter' },
  { name: 'Minecraft Dungeons', steamId: 1672970, genre: 'Acción' },
  { name: 'Minecraft Legends', steamId: 1928870, genre: 'Estrategia' },
  { name: 'Ori and the Will of the Wisps', steamId: 1057090, genre: 'Plataformas' },
  { name: 'Ori and the Blind Forest', steamId: 261570, genre: 'Plataformas' },
  { name: 'The Outer Worlds', steamId: 578650, genre: 'RPG' },
  { name: 'Starfield', steamId: 1716740, genre: 'RPG' },
  { name: 'Fallout 76', steamId: 1151340, genre: 'RPG' },
  { name: 'Fallout 4', steamId: 377160, genre: 'RPG' },
  { name: 'State of Decay 2', steamId: 495420, genre: 'Supervivencia' },
  { name: 'Quantum Break', steamId: 474960, genre: 'Acción' },
  { name: 'Sunset Overdrive', steamId: 847370, genre: 'Acción' },
  { name: 'The Ascent', steamId: 979690, genre: 'Shooter' },
  { name: 'Battletoads', steamId: 1244950, genre: 'Acción' },
  { name: 'As Dusk Falls', steamId: 1341820, genre: 'Aventura' },
  { name: "Super Lucky's Tale", steamId: 847360, genre: 'Plataformas' },
  { name: 'Wasteland 3', steamId: 719040, genre: 'RPG' },
  { name: 'Halo Wars: Definitive Edition', steamId: 459220, genre: 'Estrategia' },
  // — Bethesda / ZeniMax (hoy Microsoft) —
  { name: 'The Elder Scrolls V: Skyrim Special Edition', steamId: 489830, genre: 'RPG' },
  { name: 'DOOM', steamId: 379720, genre: 'Shooter' },
  { name: 'DOOM Eternal', steamId: 782330, genre: 'Shooter' },
  { name: 'Dishonored 2', steamId: 403640, genre: 'Acción' },
  { name: 'Prey', steamId: 480490, genre: 'Shooter' },
  { name: 'Wolfenstein II: The New Colossus', steamId: 612880, genre: 'Shooter' },
  // — AAA multiplataforma (grandes candidatos a bug en MS Store) —
  { name: 'Cyberpunk 2077', steamId: 1091500, genre: 'RPG' },
  { name: 'ELDEN RING', steamId: 1245620, genre: 'RPG' },
  { name: 'Hogwarts Legacy', steamId: 990080, genre: 'RPG' },
  { name: "Baldur's Gate 3", steamId: 1086940, genre: 'RPG' },
  { name: 'Red Dead Redemption 2', steamId: 1174180, genre: 'Aventura' },
  { name: 'Grand Theft Auto V', steamId: 271590, genre: 'Acción' },
  { name: 'The Witcher 3: Wild Hunt', steamId: 292030, genre: 'RPG' },
  { name: 'Sekiro: Shadows Die Twice', steamId: 814380, genre: 'Acción' },
  { name: 'Star Wars Jedi: Survivor', steamId: 1774580, genre: 'Acción' },
  { name: 'Star Wars Jedi: Fallen Order', steamId: 1172380, genre: 'Acción' },
  { name: 'Resident Evil 4', steamId: 2050650, genre: 'Terror' },
  { name: 'Resident Evil Village', steamId: 1196590, genre: 'Terror' },
  { name: 'Devil May Cry 5', steamId: 601150, genre: 'Acción' },
  { name: 'Monster Hunter: World', steamId: 582010, genre: 'Acción' },
  { name: 'Monster Hunter: Rise', steamId: 1446780, genre: 'Acción' },
  { name: 'Monster Hunter Wilds', steamId: 2246340, genre: 'Acción' },
  { name: 'Street Fighter 6', steamId: 1364780, genre: 'Lucha' },
  { name: 'Mortal Kombat 1', steamId: 1971870, genre: 'Lucha' },
  { name: 'TEKKEN 8', steamId: 1778820, genre: 'Lucha' },
  { name: 'Diablo IV', steamId: 2344520, genre: 'RPG' },
  { name: 'Final Fantasy VII Remake', steamId: 1462040, genre: 'JRPG' },
  { name: "Dragon's Dogma 2", steamId: 2054970, genre: 'RPG' },
  { name: 'Remnant 2', steamId: 1282100, genre: 'Shooter' },
  { name: 'Lies of P', steamId: 1627720, genre: 'Acción' },
  { name: 'Stray', steamId: 1332010, genre: 'Aventura' },
  { name: 'Atomic Heart', steamId: 668580, genre: 'Shooter' },
  { name: 'Warhammer 40,000: Space Marine 2', steamId: 2183900, genre: 'Shooter' },
  { name: 'Kingdom Come: Deliverance II', steamId: 1771300, genre: 'RPG' },
  { name: 'Indiana Jones and the Great Circle', steamId: 2677660, genre: 'Aventura', msTerm: 'Indiana Jones' },
  { name: 'Call of Duty: Black Ops 6', steamId: 4384550, genre: 'Shooter', msTerm: 'Black Ops 6' },
  { name: 'Immortals Fenyx Rising', steamId: 2221920, genre: 'Aventura' },
  { name: "Assassin's Creed Mirage", steamId: 3035570, genre: 'Acción' },
  { name: "Crash Bandicoot 4: It's About Time", steamId: 1378990, genre: 'Plataformas' },
  { name: 'Frostpunk 2', steamId: 1601580, genre: 'Estrategia' },
  { name: 'Ghostrunner 2', steamId: 2144740, genre: 'Acción' },
  { name: 'Sea of Stars', steamId: 1244090, genre: 'JRPG' },
  { name: "Death Stranding Director's Cut", steamId: 1850570, genre: 'Aventura' },
  // — Microsoft Store first-party / multiplataforma (más títulos con precio ARS) —
  { name: 'Microsoft Flight Simulator', steamId: 1250410, genre: 'Simulación', msTerm: 'Microsoft Flight Simulator 40th' },
  { name: 'Microsoft Flight Simulator 2024', steamId: 2537590, genre: 'Simulación', msTerm: 'Microsoft Flight Simulator 2024' },
  { name: 'Killer Instinct', steamId: 577940, genre: 'Lucha' },
  { name: "Hellblade: Senua's Sacrifice", steamId: 414340, genre: 'Aventura' },
  { name: "Senua's Saga: Hellblade II", steamId: 2461850, genre: 'Aventura' },
  { name: 'Octopath Traveler II', steamId: 1971650, genre: 'JRPG' },
  // — Indie / multiplataforma —
  { name: 'Cuphead', steamId: 268910, genre: 'Plataformas' },
  { name: 'Hollow Knight', steamId: 367520, genre: 'Plataformas' },
  { name: 'Hades', steamId: 1145360, genre: 'Roguelike' },
  { name: 'Hades II', steamId: 1145350, genre: 'Roguelike' },
  { name: 'Stardew Valley', steamId: 413150, genre: 'Simulación' },
  { name: 'Terraria', steamId: 105600, genre: 'Supervivencia' },
  { name: 'Slay the Spire', steamId: 646570, genre: 'Roguelike' },
  { name: 'Celeste', steamId: 504230, genre: 'Plataformas' },
  { name: 'Weird West', steamId: 1097350, genre: 'RPG' },
  { name: "Death's Door", steamId: 894020, genre: 'Aventura' },
  { name: 'Ghostrunner', steamId: 1139900, genre: 'Acción' },
  { name: 'Two Point Hospital', steamId: 535930, genre: 'Simulación' },
  { name: 'Two Point Campus', steamId: 1649080, genre: 'Simulación' },
  { name: 'Vampire Survivors', steamId: 1794680, genre: 'Roguelike' },
  { name: 'PowerWash Simulator', steamId: 1290000, genre: 'Simulación' },
  { name: 'DAVE THE DIVER', steamId: 1868140, genre: 'Aventura' },
  { name: 'Cult of the Lamb', steamId: 1313140, genre: 'Roguelike' },
  { name: 'Subnautica', steamId: 264710, genre: 'Supervivencia' },
  { name: 'Satisfactory', steamId: 526870, genre: 'Simulación' },
  { name: 'Deep Rock Galactic', steamId: 548430, genre: 'Shooter' },
  { name: 'Valheim', steamId: 892970, genre: 'Supervivencia' },
  { name: 'Sons of the Forest', steamId: 1326470, genre: 'Supervivencia' },
  { name: 'Palworld', steamId: 1623730, genre: 'Supervivencia' },
  { name: 'Manor Lords', steamId: 1363080, genre: 'Estrategia' },
  { name: 'Enshrouded', steamId: 1203620, genre: 'Supervivencia' },
  { name: 'A Way Out', steamId: 1222700, genre: 'Aventura' },
  { name: 'Yakuza 0', steamId: 638970, genre: 'Acción' },
  { name: 'Like a Dragon Gaiden: The Man Who Erased His Name', steamId: 2375550, genre: 'Acción' },
  { name: 'Judgment', steamId: 2058180, genre: 'Acción' },
  { name: 'Sifu', steamId: 2138710, genre: 'Acción' },
  { name: 'Control', steamId: 870780, genre: 'Acción' },
  { name: 'DREDGE', steamId: 1562430, genre: 'Aventura' },
  { name: 'TUNIC', steamId: 553420, genre: 'Aventura' },
  // — JRPG / otros también en Epic —
  { name: 'Persona 3 Reload', steamId: 2161700, genre: 'JRPG' },
  { name: 'Persona 5 Royal', steamId: 1687950, genre: 'JRPG' },
  { name: 'Persona 4 Golden', steamId: 1113000, genre: 'JRPG' },
  { name: 'Soul Hackers 2', steamId: 1777620, genre: 'JRPG' },
  { name: 'Like a Dragon: Ishin!', steamId: 1805480, genre: 'Acción' },
  { name: 'Like a Dragon: Infinite Wealth', steamId: 2072450, genre: 'RPG' },
  { name: 'Scarlet Nexus', steamId: 775500, genre: 'Acción' },
  { name: 'Crash Bandicoot N. Sane Trilogy', steamId: 731490, genre: 'Plataformas' },
  { name: 'Spyro Reignited Trilogy', steamId: 996580, genre: 'Plataformas' },
  { name: 'Nier: Automata', steamId: 524220, genre: 'JRPG' },
  { name: 'It Takes Two', steamId: 1426210, genre: 'Aventura' },
  // — Ports de PlayStation en PC (muy presentes en MS Store) —
  { name: 'God of War', steamId: 1593500, genre: 'Acción' },
  { name: 'God of War Ragnarök', steamId: 2322010, genre: 'Acción' },
  { name: "Marvel's Spider-Man Remastered", steamId: 1817070, genre: 'Acción' },
  { name: "Marvel's Spider-Man: Miles Morales", steamId: 1817190, genre: 'Acción' },
  { name: 'Horizon Zero Dawn', steamId: 1151640, genre: 'Aventura' },
  { name: 'Horizon Forbidden West', steamId: 2420110, genre: 'Aventura' },
  { name: 'The Last of Us Part I', steamId: 1888930, genre: 'Aventura' },
  { name: 'Ghost of Tsushima', steamId: 2215430, genre: 'Acción' },
  { name: 'Days Gone', steamId: 1259420, genre: 'Aventura' },
  { name: 'Detroit: Become Human', steamId: 1222140, genre: 'Aventura' },
  { name: 'Returnal', steamId: 1649240, genre: 'Shooter' },
  { name: 'Ratchet & Clank: Rift Apart', steamId: 1895880, genre: 'Plataformas' },
  // — DC / Warner Bros —
  { name: 'Batman: Arkham Knight', steamId: 208650, genre: 'Acción' },
  { name: 'Batman: Arkham Asylum', steamId: 35140, genre: 'Acción' },
  { name: 'Batman: Arkham City', steamId: 200260, genre: 'Acción' },
  { name: 'Middle-earth: Shadow of War', steamId: 356190, genre: 'Acción' },
  { name: 'Middle-earth: Shadow of Mordor', steamId: 241930, genre: 'Acción' },
  { name: 'Mortal Kombat 11', steamId: 976310, genre: 'Lucha' },
  { name: 'Injustice 2', steamId: 627270, genre: 'Lucha' },
  // — Tomb Raider / Square Enix —
  { name: 'Shadow of the Tomb Raider', steamId: 750920, genre: 'Aventura' },
  { name: 'Rise of the Tomb Raider', steamId: 391220, genre: 'Aventura' },
  { name: 'Tomb Raider', steamId: 203160, genre: 'Aventura' },
  { name: 'FINAL FANTASY XV', steamId: 637650, genre: 'JRPG', msTerm: 'Final Fantasy XV' },
  { name: 'FINAL FANTASY XVI', steamId: 2515020, genre: 'JRPG', msTerm: 'Final Fantasy XVI' },
  { name: 'NieR Replicant', steamId: 1113560, genre: 'JRPG', msTerm: 'Nier Replicant' },
  { name: 'HITMAN World of Assassination', steamId: 1659040, genre: 'Acción', msTerm: 'Hitman' },
  // — Ubisoft —
  { name: 'Far Cry 6', steamId: 2369390, genre: 'Shooter' },
  { name: 'Far Cry 5', steamId: 552520, genre: 'Shooter' },
  { name: 'Watch Dogs 2', steamId: 447040, genre: 'Acción' },
  { name: "Assassin's Creed Valhalla", steamId: 2208920, genre: 'RPG' },
  { name: "Assassin's Creed Odyssey", steamId: 812140, genre: 'RPG' },
  { name: "Assassin's Creed Origins", steamId: 582160, genre: 'RPG' },
  { name: "Tom Clancy's Rainbow Six Siege", steamId: 359550, genre: 'Shooter' },
  // — Capcom horror —
  { name: 'Resident Evil 2', steamId: 883710, genre: 'Terror' },
  { name: 'Resident Evil 3', steamId: 952060, genre: 'Terror' },
  { name: 'Resident Evil 7: Biohazard', steamId: 418370, genre: 'Terror' },
  // — Souls / soulslike —
  { name: 'Dark Souls III', steamId: 374320, genre: 'RPG' },
  { name: 'Dark Souls: Remastered', steamId: 570940, genre: 'RPG' },
  { name: 'Dark Souls II: Scholar of the First Sin', steamId: 335300, genre: 'RPG' },
  { name: 'Nioh 2', steamId: 1325200, genre: 'Acción' },
  { name: 'Wo Long: Fallen Dynasty', steamId: 1448440, genre: 'Acción' },
  // — Bandai Namco / anime —
  { name: 'Tales of Arise', steamId: 740130, genre: 'JRPG' },
  { name: 'CODE VEIN', steamId: 678960, genre: 'RPG' },
  { name: 'DRAGON BALL Z: KAKAROT', steamId: 851850, genre: 'Acción' },
  { name: 'GUILTY GEAR -STRIVE-', steamId: 1384160, genre: 'Lucha' },
  { name: 'Persona 5 Strikers', steamId: 1382330, genre: 'Acción' },
  // — Fallout clásicos / Valve —
  { name: 'Fallout: New Vegas', steamId: 22380, genre: 'RPG' },
  { name: 'Fallout 3: Game of the Year Edition', steamId: 22370, genre: 'RPG' },
  { name: 'Left 4 Dead 2', steamId: 550, genre: 'Shooter' },
  { name: 'Portal 2', steamId: 620, genre: 'Puzzle' },
  { name: 'Half-Life 2', steamId: 220, genre: 'Shooter' },
  // — FPS / online —
  { name: 'Metro Exodus', steamId: 412020, genre: 'Shooter' },
  { name: 'Titanfall 2', steamId: 1237970, genre: 'Shooter' },
  { name: 'Apex Legends', steamId: 1172470, genre: 'Shooter' },
  { name: 'Battlefield 2042', steamId: 1517290, genre: 'Shooter' },
  { name: 'STAR WARS Battlefront II', steamId: 1237950, genre: 'Shooter' },
  { name: 'STAR WARS: Squadrons', steamId: 1222730, genre: 'Shooter' },
  { name: 'Overwatch 2', steamId: 2357570, genre: 'Shooter', msTerm: 'Overwatch' },
  { name: 'Dying Light', steamId: 239140, genre: 'Acción' },
  { name: 'Dying Light 2 Stay Human', steamId: 534380, genre: 'Acción' },
  { name: 'Borderlands 3', steamId: 397540, genre: 'Shooter' },
  // — Supervivencia / sandbox —
  { name: 'No Man\'s Sky', steamId: 275850, genre: 'Supervivencia' },
  { name: 'Rust', steamId: 252490, genre: 'Supervivencia' },
  { name: 'ARK: Survival Evolved', steamId: 346110, genre: 'Supervivencia' },
  { name: '7 Days to Die', steamId: 251570, genre: 'Supervivencia' },
  { name: 'Project Zomboid', steamId: 108600, genre: 'Supervivencia' },
  { name: "Don't Starve Together", steamId: 322330, genre: 'Supervivencia' },
  // — Simulación / estrategia —
  { name: 'RimWorld', steamId: 294100, genre: 'Simulación' },
  { name: 'Factorio', steamId: 427520, genre: 'Estrategia' },
  { name: 'Cities: Skylines', steamId: 255710, genre: 'Simulación' },

  // ════════════ AMPLIACIÓN MASIVA (catálogo MS Store completo) ════════════
  // — Más Xbox / Microsoft first-party —
  { name: 'Ryse: Son of Rome', steamId: 302510, genre: 'Acción' },
  { name: 'Wasteland 2: Director\'s Cut', steamId: 404730, genre: 'RPG' },
  { name: 'Pillars of Eternity', steamId: 291650, genre: 'RPG' },
  { name: 'Pillars of Eternity II: Deadfire', steamId: 560130, genre: 'RPG' },
  { name: 'Tell Me Why', steamId: 1180660, genre: 'Aventura' },
  { name: 'Age of Empires: Definitive Edition', steamId: 1017900, genre: 'Estrategia' },
  // — Bethesda / ZeniMax (hoy Microsoft) —
  { name: 'The Elder Scrolls III: Morrowind', steamId: 22320, genre: 'RPG' },
  { name: 'The Elder Scrolls IV: Oblivion Game of the Year Edition', steamId: 22330, genre: 'RPG' },
  { name: 'DOOM 3', steamId: 208200, genre: 'Shooter' },
  { name: 'Quake', steamId: 2310, genre: 'Shooter' },
  { name: 'Rage 2', steamId: 548570, genre: 'Shooter' },
  { name: 'Dishonored', steamId: 205100, genre: 'Acción' },
  { name: 'Dishonored: Death of the Outsider', steamId: 614570, genre: 'Acción' },
  { name: 'Wolfenstein: The New Order', steamId: 201810, genre: 'Shooter' },
  { name: 'Wolfenstein: The Old Blood', steamId: 350080, genre: 'Shooter' },
  { name: 'Wolfenstein: Youngblood', steamId: 1056960, genre: 'Shooter' },
  { name: 'The Evil Within', steamId: 268050, genre: 'Terror' },
  { name: 'The Evil Within 2', steamId: 601430, genre: 'Terror' },
  { name: 'Fallout Shelter', steamId: 588430, genre: 'Simulación' },
  // — EA —
  { name: 'Battlefield V', steamId: 1238810, genre: 'Shooter' },
  { name: 'Battlefield 1', steamId: 1238840, genre: 'Shooter' },
  { name: 'Battlefield 4', steamId: 1238860, genre: 'Shooter' },
  { name: 'Need for Speed: Unbound', steamId: 1846380, genre: 'Carreras' },
  { name: 'Need for Speed Heat', steamId: 1222680, genre: 'Carreras' },
  { name: 'Need for Speed Payback', steamId: 1262580, genre: 'Carreras' },
  { name: 'Need for Speed Most Wanted', steamId: 1262560, genre: 'Carreras' },
  { name: 'Dead Space', steamId: 1693980, genre: 'Terror' },
  { name: 'Mass Effect Legendary Edition', steamId: 1328670, genre: 'RPG' },
  { name: 'Dragon Age: Inquisition', steamId: 1222690, genre: 'RPG' },
  { name: 'Dragon Age: The Veilguard', steamId: 1845910, genre: 'RPG' },
  { name: 'Dragon Age: Origins', steamId: 17450, genre: 'RPG' },
  { name: 'The Sims 4', steamId: 1222670, genre: 'Simulación' },
  { name: 'Command & Conquer Remastered Collection', steamId: 1213210, genre: 'Estrategia' },
  { name: 'Unravel Two', steamId: 1225570, genre: 'Plataformas' },
  { name: 'Wild Hearts', steamId: 1938010, genre: 'Acción' },
  { name: 'EA SPORTS WRC', steamId: 1849250, genre: 'Carreras' },
  { name: 'F1 24', steamId: 2488620, genre: 'Carreras' },
  { name: 'Mirror\'s Edge Catalyst', steamId: 1233570, genre: 'Acción' },
  // — Ubisoft —
  { name: 'Far Cry 3', steamId: 220240, genre: 'Shooter' },
  { name: 'Far Cry 4', steamId: 298110, genre: 'Shooter' },
  { name: 'Far Cry Primal', steamId: 371660, genre: 'Shooter' },
  { name: 'Far Cry New Dawn', steamId: 939960, genre: 'Shooter' },
  { name: 'Watch Dogs', steamId: 243470, genre: 'Acción' },
  { name: 'Watch Dogs: Legion', steamId: 2239550, genre: 'Acción' },
  { name: "Assassin's Creed II", steamId: 33230, genre: 'Acción' },
  { name: "Assassin's Creed Brotherhood", steamId: 48190, genre: 'Acción' },
  { name: "Assassin's Creed Revelations", steamId: 201870, genre: 'Acción' },
  { name: "Assassin's Creed III Remastered", steamId: 208480, genre: 'Acción' },
  { name: "Assassin's Creed Unity", steamId: 289650, genre: 'Acción' },
  { name: "Assassin's Creed Syndicate", steamId: 368500, genre: 'Acción' },
  { name: "Assassin's Creed Rogue", steamId: 311560, genre: 'Acción' },
  { name: "Assassin's Creed IV Black Flag", steamId: 242050, genre: 'Acción' },
  { name: "Tom Clancy's The Division", steamId: 365590, genre: 'Shooter' },
  { name: "Tom Clancy's Ghost Recon Wildlands", steamId: 460930, genre: 'Shooter' },
  { name: "Tom Clancy's Ghost Recon Breakpoint", steamId: 2231380, genre: 'Shooter' },
  { name: 'For Honor', steamId: 304390, genre: 'Lucha' },
  { name: 'Anno 1800', steamId: 916440, genre: 'Estrategia' },
  { name: 'Child of Light', steamId: 256290, genre: 'RPG' },
  { name: 'Rayman Legends', steamId: 242550, genre: 'Plataformas' },
  { name: 'Riders Republic', steamId: 2290180, genre: 'Deportes' },
  // — Ports de PlayStation / Sony (PC) —
  { name: 'Uncharted: Legacy of Thieves Collection', steamId: 1659420, genre: 'Acción' },
  { name: 'HELLDIVERS 2', steamId: 553850, genre: 'Shooter' },
  { name: 'Until Dawn', steamId: 2172010, genre: 'Terror' },
  // — Capcom —
  { name: 'Resident Evil', steamId: 304240, genre: 'Terror' },
  { name: 'Resident Evil 0', steamId: 339340, genre: 'Terror' },
  { name: 'Resident Evil 5', steamId: 21690, genre: 'Terror' },
  { name: 'Resident Evil 6', steamId: 221040, genre: 'Terror' },
  { name: 'Resident Evil Revelations', steamId: 222480, genre: 'Terror' },
  { name: 'Resident Evil Revelations 2', steamId: 287290, genre: 'Terror' },
  { name: 'Devil May Cry 4 Special Edition', steamId: 329050, genre: 'Acción' },
  { name: 'Devil May Cry HD Collection', steamId: 631510, genre: 'Acción' },
  { name: 'DmC: Devil May Cry', steamId: 220440, genre: 'Acción' },
  { name: 'Street Fighter V', steamId: 310950, genre: 'Lucha' },
  { name: 'Okami HD', steamId: 587620, genre: 'Aventura' },
  { name: "Dragon's Dogma: Dark Arisen", steamId: 367500, genre: 'RPG' },
  { name: 'Dead Rising 4', steamId: 543460, genre: 'Acción' },
  { name: 'Exoprimal', steamId: 1286320, genre: 'Shooter' },
  { name: 'Monster Hunter Stories 2: Wings of Ruin', steamId: 1277400, genre: 'RPG' },
  // — Square Enix —
  { name: 'FINAL FANTASY VII', steamId: 39140, genre: 'JRPG' },
  { name: 'FINAL FANTASY VIII Remastered', steamId: 39150, genre: 'JRPG' },
  { name: 'FINAL FANTASY IX', steamId: 377840, genre: 'JRPG' },
  { name: 'FINAL FANTASY X/X-2 HD Remaster', steamId: 359870, genre: 'JRPG' },
  { name: 'FINAL FANTASY XII The Zodiac Age', steamId: 595520, genre: 'JRPG' },
  { name: 'FINAL FANTASY XIII', steamId: 292120, genre: 'JRPG' },
  { name: 'Forspoken', steamId: 1680880, genre: 'Acción' },
  { name: 'DRAGON QUEST XI S: Echoes of an Elusive Age', steamId: 1295510, genre: 'JRPG' },
  { name: 'Dragon Quest Builders 2', steamId: 1072420, genre: 'Aventura' },
  { name: 'Chrono Trigger', steamId: 613830, genre: 'JRPG' },
  { name: 'Triangle Strategy', steamId: 1850510, genre: 'JRPG' },
  { name: 'Life is Strange', steamId: 319630, genre: 'Aventura' },
  { name: 'Life is Strange 2', steamId: 532210, genre: 'Aventura' },
  { name: 'Life is Strange: True Colors', steamId: 936790, genre: 'Aventura' },
  { name: 'Sleeping Dogs: Definitive Edition', steamId: 202170, genre: 'Acción' },
  { name: 'Just Cause 3', steamId: 225540, genre: 'Acción' },
  { name: 'Just Cause 4', steamId: 517630, genre: 'Acción' },
  { name: "Marvel's Guardians of the Galaxy", steamId: 1088850, genre: 'Acción' },
  { name: 'Outriders', steamId: 680420, genre: 'Shooter' },
  // — Bandai Namco —
  { name: 'TEKKEN 7', steamId: 389730, genre: 'Lucha' },
  { name: 'SOULCALIBUR VI', steamId: 544750, genre: 'Lucha' },
  { name: 'Ace Combat 7: Skies Unknown', steamId: 502500, genre: 'Simulación' },
  { name: 'DRAGON BALL FighterZ', steamId: 678950, genre: 'Lucha' },
  { name: 'DRAGON BALL Xenoverse 2', steamId: 454650, genre: 'Lucha' },
  { name: 'NARUTO SHIPPUDEN: Ultimate Ninja STORM 4', steamId: 349040, genre: 'Lucha' },
  { name: 'Tales of Zestiria', steamId: 351970, genre: 'JRPG' },
  { name: 'Tales of Berseria', steamId: 429660, genre: 'JRPG' },
  { name: 'Tales of Vesperia: Definitive Edition', steamId: 738540, genre: 'JRPG' },
  { name: 'ARMORED CORE VI FIRES OF RUBICON', steamId: 1888160, genre: 'Acción' },
  { name: 'Little Nightmares', steamId: 424840, genre: 'Terror' },
  { name: 'Little Nightmares II', steamId: 860510, genre: 'Terror' },
  { name: 'Ni no Kuni: Wrath of the White Witch Remastered', steamId: 798460, genre: 'RPG' },
  { name: 'Ni no Kuni II: Revenant Kingdom', steamId: 589360, genre: 'RPG' },
  // — Koei Tecmo —
  { name: 'Nioh: Complete Edition', steamId: 485510, genre: 'Acción' },
  { name: 'DEAD OR ALIVE 6', steamId: 838380, genre: 'Lucha' },
  // — Sega —
  { name: 'Yakuza Kiwami', steamId: 834530, genre: 'Acción' },
  { name: 'Yakuza Kiwami 2', steamId: 927380, genre: 'Acción' },
  { name: 'Yakuza 3 Remastered', steamId: 1088710, genre: 'Acción' },
  { name: 'Yakuza 4 Remastered', steamId: 1105500, genre: 'Acción' },
  { name: 'Yakuza 5 Remastered', steamId: 1105510, genre: 'Acción' },
  { name: 'Yakuza 6: The Song of Life', steamId: 1388590, genre: 'Acción' },
  { name: 'Lost Judgment', steamId: 2058190, genre: 'Acción' },
  { name: 'Sonic Generations', steamId: 71340, genre: 'Plataformas' },
  { name: 'Sonic Mania', steamId: 584400, genre: 'Plataformas' },
  { name: 'Total War: WARHAMMER III', steamId: 1142710, genre: 'Estrategia' },
  { name: 'Total War: THREE KINGDOMS', steamId: 779340, genre: 'Estrategia' },
  { name: 'Football Manager 2024', steamId: 2252570, genre: 'Deportes' },
  { name: 'Company of Heroes 3', steamId: 1677280, genre: 'Estrategia' },
  { name: 'HUMANKIND', steamId: 1124300, genre: 'Estrategia' },
  { name: 'Bayonetta', steamId: 460790, genre: 'Acción' },
  { name: 'Vanquish', steamId: 460810, genre: 'Shooter' },
  { name: 'Valkyria Chronicles 4', steamId: 790820, genre: 'JRPG' },
  { name: 'Streets of Rage 4', steamId: 985890, genre: 'Acción' },
  // — Konami —
  { name: 'METAL GEAR SOLID V: The Phantom Pain', steamId: 287700, genre: 'Acción' },
  { name: 'METAL GEAR SOLID V: Ground Zeroes', steamId: 311340, genre: 'Acción' },
  { name: 'Silent Hill 2', steamId: 2124490, genre: 'Terror' },
  { name: 'Yu-Gi-Oh! Master Duel', steamId: 1449850, genre: 'Estrategia' },
  { name: 'eFootball 2025', steamId: 1665460, genre: 'Deportes' },
  // — 2K —
  { name: 'BioShock Remastered', steamId: 409710, genre: 'Shooter' },
  { name: 'BioShock 2 Remastered', steamId: 409720, genre: 'Shooter' },
  { name: 'BioShock Infinite', steamId: 8870, genre: 'Shooter' },
  { name: 'Borderlands 2', steamId: 49520, genre: 'Shooter' },
  { name: 'Borderlands: Game of the Year Edition', steamId: 8980, genre: 'Shooter' },
  { name: 'Borderlands: The Pre-Sequel', steamId: 261640, genre: 'Shooter' },
  { name: "Tiny Tina's Wonderlands", steamId: 1286680, genre: 'RPG' },
  { name: 'XCOM 2', steamId: 268500, genre: 'Estrategia' },
  { name: 'XCOM: Enemy Unknown', steamId: 200510, genre: 'Estrategia' },
  { name: 'Sid Meier\'s Civilization VI', steamId: 289070, genre: 'Estrategia' },
  { name: 'Sid Meier\'s Civilization V', steamId: 8930, genre: 'Estrategia' },
  { name: 'Sid Meier\'s Civilization VII', steamId: 1295660, genre: 'Estrategia' },
  { name: 'Mafia: Definitive Edition', steamId: 1030840, genre: 'Acción' },
  { name: 'Mafia II', steamId: 50130, genre: 'Acción' },
  { name: 'Mafia III', steamId: 360430, genre: 'Acción' },
  { name: "Marvel's Midnight Suns", steamId: 368260, genre: 'Estrategia' },
  // — Rockstar / Take-Two —
  { name: 'Red Dead Redemption', steamId: 2668510, genre: 'Aventura' },
  { name: 'Grand Theft Auto IV: The Complete Edition', steamId: 12210, genre: 'Acción' },
  { name: 'L.A. Noire', steamId: 110800, genre: 'Aventura' },
  { name: 'Max Payne 3', steamId: 204100, genre: 'Shooter' },
  // — CD Projekt —
  { name: 'The Witcher', steamId: 20900, genre: 'RPG' },
  { name: 'The Witcher 2: Assassins of Kings Enhanced Edition', steamId: 20920, genre: 'RPG' },
  // — Paradox —
  { name: 'Cities: Skylines II', steamId: 949230, genre: 'Simulación' },
  { name: 'Hearts of Iron IV', steamId: 394360, genre: 'Estrategia' },
  { name: 'Europa Universalis IV', steamId: 236850, genre: 'Estrategia' },
  { name: 'Stellaris', steamId: 281990, genre: 'Estrategia' },
  { name: 'Crusader Kings III', steamId: 1158310, genre: 'Estrategia' },
  { name: 'Surviving Mars', steamId: 464920, genre: 'Simulación' },
  { name: 'Prison Architect', steamId: 233450, genre: 'Simulación' },
  // — Indie / multiplataforma (muchos en MS Store) —
  { name: 'Brotato', steamId: 1942280, genre: 'Roguelike' },
  { name: 'Balatro', steamId: 2379780, genre: 'Roguelike' },
  { name: 'Dead Cells', steamId: 588650, genre: 'Roguelike' },
  { name: 'Rogue Legacy 2', steamId: 1253920, genre: 'Roguelike' },
  { name: 'Risk of Rain 2', steamId: 632360, genre: 'Roguelike' },
  { name: 'Risk of Rain', steamId: 248820, genre: 'Roguelike' },
  { name: 'Deep Rock Galactic: Survivor', steamId: 2321470, genre: 'Roguelike' },
  { name: 'The Binding of Isaac: Rebirth', steamId: 250900, genre: 'Roguelike' },
  { name: 'Blasphemous', steamId: 774361, genre: 'Plataformas' },
  { name: 'Blasphemous 2', steamId: 2114740, genre: 'Plataformas' },
  { name: 'Darkest Dungeon', steamId: 262060, genre: 'Roguelike' },
  { name: 'Darkest Dungeon II', steamId: 1940340, genre: 'Roguelike' },
  { name: 'Monster Train', steamId: 1102190, genre: 'Roguelike' },
  { name: 'Into the Breach', steamId: 590380, genre: 'Estrategia' },
  { name: 'FTL: Faster Than Light', steamId: 212680, genre: 'Roguelike' },
  { name: 'Baba Is You', steamId: 736260, genre: 'Puzzle' },
  { name: 'Return of the Obra Dinn', steamId: 653530, genre: 'Puzzle' },
  { name: 'Outer Wilds', steamId: 753640, genre: 'Aventura' },
  { name: 'Firewatch', steamId: 383870, genre: 'Aventura' },
  { name: 'What Remains of Edith Finch', steamId: 501300, genre: 'Aventura' },
  { name: 'Abzu', steamId: 384190, genre: 'Aventura' },
  { name: 'A Short Hike', steamId: 1055540, genre: 'Aventura' },
  { name: 'Spiritfarer', steamId: 972660, genre: 'Simulación' },
  { name: 'Gris', steamId: 683320, genre: 'Plataformas' },
  { name: 'Limbo', steamId: 48000, genre: 'Puzzle' },
  { name: 'Super Meat Boy', steamId: 40800, genre: 'Plataformas' },
  { name: 'Braid', steamId: 26800, genre: 'Puzzle' },
  { name: 'Fez', steamId: 224760, genre: 'Puzzle' },
  { name: 'Undertale', steamId: 391540, genre: 'RPG' },
  { name: 'OMORI', steamId: 1150690, genre: 'RPG' },
  { name: 'Katana ZERO', steamId: 460950, genre: 'Acción' },
  { name: 'Hotline Miami', steamId: 219150, genre: 'Acción' },
  { name: 'Hotline Miami 2: Wrong Number', steamId: 274170, genre: 'Acción' },
  { name: 'My Friend Pedro', steamId: 557340, genre: 'Plataformas' },
  { name: 'Broforce', steamId: 274190, genre: 'Plataformas' },
  { name: 'Overcooked', steamId: 448510, genre: 'Simulación' },
  { name: 'Overcooked 2', steamId: 728880, genre: 'Simulación' },
  { name: 'Human Fall Flat', steamId: 477160, genre: 'Puzzle' },
  { name: 'Gang Beasts', steamId: 285900, genre: 'Lucha' },
  { name: 'Fall Guys', steamId: 1097150, genre: 'Acción' },
  { name: 'Among Us', steamId: 945360, genre: 'Puzzle' },
  { name: 'Phasmophobia', steamId: 739630, genre: 'Terror' },
  { name: 'Lethal Company', steamId: 1966720, genre: 'Terror' },
  { name: 'Raft', steamId: 648800, genre: 'Supervivencia' },
  { name: 'Green Hell', steamId: 815370, genre: 'Supervivencia' },
  { name: 'The Forest', steamId: 242760, genre: 'Supervivencia' },
  { name: 'Stranded Deep', steamId: 313120, genre: 'Supervivencia' },
  { name: 'Subnautica: Below Zero', steamId: 848450, genre: 'Supervivencia' },
  { name: "Don't Starve", steamId: 219740, genre: 'Supervivencia' },
  { name: 'Oxygen Not Included', steamId: 457140, genre: 'Simulación' },
  { name: 'Potion Craft', steamId: 1210320, genre: 'Simulación' },
  { name: 'Graveyard Keeper', steamId: 599140, genre: 'Simulación' },
  { name: 'My Time at Portia', steamId: 666140, genre: 'Simulación' },
  { name: 'My Time at Sandrock', steamId: 1084600, genre: 'Simulación' },
  { name: 'Coral Island', steamId: 1158160, genre: 'Simulación' },
  { name: 'Core Keeper', steamId: 1621690, genre: 'Supervivencia' },
  { name: 'Pacific Drive', steamId: 1458140, genre: 'Supervivencia' },
  { name: 'Frostpunk', steamId: 323190, genre: 'Estrategia' },
  { name: 'Surviving the Aftermath', steamId: 684450, genre: 'Estrategia' },
  { name: 'This War of Mine', steamId: 282070, genre: 'Estrategia' },
  { name: 'Northgard', steamId: 466560, genre: 'Estrategia' },
  { name: 'Timberborn', steamId: 1062090, genre: 'Simulación' },
  { name: 'Against the Storm', steamId: 1336490, genre: 'Estrategia' },
  { name: 'Dyson Sphere Program', steamId: 1366540, genre: 'Estrategia' },
  { name: 'Grim Dawn', steamId: 219990, genre: 'RPG' },
  { name: 'Path of Exile', steamId: 238960, genre: 'RPG' },
  { name: 'Path of Exile 2', steamId: 2694490, genre: 'RPG' },
  { name: 'Torchlight II', steamId: 200710, genre: 'RPG' },
  { name: 'Planet Coaster', steamId: 493340, genre: 'Simulación' },
  { name: 'Planet Zoo', steamId: 703080, genre: 'Simulación' },
  { name: 'Jurassic World Evolution 2', steamId: 1244460, genre: 'Simulación' },
  { name: 'Slime Rancher', steamId: 433340, genre: 'Simulación' },
  { name: 'Slime Rancher 2', steamId: 1657630, genre: 'Simulación' },
  { name: 'Untitled Goose Game', steamId: 837470, genre: 'Puzzle' },
  { name: 'A Plague Tale: Innocence', steamId: 752590, genre: 'Aventura' },
  { name: 'A Plague Tale: Requiem', steamId: 1182900, genre: 'Aventura' },
  { name: 'Metro 2033 Redux', steamId: 286690, genre: 'Shooter' },
  { name: 'Metro: Last Light Redux', steamId: 287390, genre: 'Shooter' },
  { name: 'Deus Ex: Mankind Divided', steamId: 337000, genre: 'Acción' },
  { name: 'Deus Ex: Human Revolution - Director\'s Cut', steamId: 238010, genre: 'Acción' },
  { name: 'Thief', steamId: 239160, genre: 'Acción' },
  { name: 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', steamId: 1643320, genre: 'Shooter' },
  { name: 'Divinity: Original Sin 2 - Definitive Edition', steamId: 435150, genre: 'RPG' },
  { name: 'Pathfinder: Wrath of the Righteous', steamId: 1184370, genre: 'RPG' },
  { name: 'The Long Dark', steamId: 305620, genre: 'Supervivencia' },
  { name: 'Pummel Party', steamId: 880940, genre: 'Acción' },
  { name: 'Euro Truck Simulator 2', steamId: 227300, genre: 'Simulación' },
  { name: 'American Truck Simulator', steamId: 270880, genre: 'Simulación' },
  { name: 'Car Mechanic Simulator 2021', steamId: 1190000, genre: 'Simulación' },
  { name: 'House Flipper', steamId: 613100, genre: 'Simulación' },
  { name: 'Kenshi', steamId: 233860, genre: 'RPG' },
  { name: 'Mount & Blade II: Bannerlord', steamId: 261550, genre: 'RPG' },
  { name: 'Disco Elysium - The Final Cut', steamId: 632470, genre: 'RPG' },
  { name: 'Night in the Woods', steamId: 481510, genre: 'Aventura' },
  { name: 'Oxenfree', steamId: 388880, genre: 'Aventura' },
  { name: 'Terminator: Resistance', steamId: 954740, genre: 'Shooter' },
  { name: 'High On Life', steamId: 1583230, genre: 'Shooter' },
  { name: 'ULTRAKILL', steamId: 1229490, genre: 'Shooter' },
  { name: 'Space Engineers', steamId: 244850, genre: 'Simulación' },
  { name: 'Starbound', steamId: 211820, genre: 'Supervivencia' },
  { name: 'Astroneer', steamId: 361420, genre: 'Supervivencia' },
  { name: 'Hardspace: Shipbreaker', steamId: 1161580, genre: 'Simulación' },
  { name: 'Kerbal Space Program', steamId: 220200, genre: 'Simulación' },
  { name: 'DCS World', steamId: 223750, genre: 'Simulación' },
  { name: 'BeamNG.drive', steamId: 284160, genre: 'Carreras' },
  { name: 'Assetto Corsa', steamId: 244210, genre: 'Carreras' },
  { name: 'Assetto Corsa Competizione', steamId: 805550, genre: 'Carreras' },
  { name: 'DiRT Rally 2.0', steamId: 690790, genre: 'Carreras' },
  { name: 'War Thunder', steamId: 236390, genre: 'Simulación' },
  { name: 'World of Warships', steamId: 552990, genre: 'Simulación' },
  { name: 'Counter-Strike 2', steamId: 730, genre: 'Shooter' },
  { name: 'Dota 2', steamId: 570, genre: 'Estrategia' },
  { name: 'Team Fortress 2', steamId: 440, genre: 'Shooter' },
  { name: 'Destiny 2', steamId: 1085660, genre: 'Shooter' },
  { name: 'Warframe', steamId: 230410, genre: 'Shooter' },
  { name: 'Paladins', steamId: 444090, genre: 'Shooter' },
  { name: 'Brawlhalla', steamId: 291550, genre: 'Lucha' },
  { name: 'MultiVersus', steamId: 1818750, genre: 'Lucha' },
  { name: 'THE FINALS', steamId: 2073850, genre: 'Shooter' },
  { name: 'Marvel Rivals', steamId: 2767030, genre: 'Shooter' },
  { name: 'PUBG: BATTLEGROUNDS', steamId: 578080, genre: 'Shooter' },
  { name: 'Call of Duty: Modern Warfare III', steamId: 1938090, genre: 'Shooter' },
  { name: 'Rocket League', steamId: 252950, genre: 'Deportes' },
  { name: 'A Hat in Time', steamId: 253230, genre: 'Plataformas' },
  { name: 'Yooka-Laylee', steamId: 360830, genre: 'Plataformas' },
  { name: 'Guacamelee! 2', steamId: 534550, genre: 'Plataformas' },
  { name: 'Sable', steamId: 757310, genre: 'Aventura' },
  { name: 'Journey', steamId: 638230, genre: 'Aventura' },
  { name: 'Kena: Bridge of Spirits', steamId: 1954200, genre: 'Aventura' },
  { name: 'Farming Simulator 22', steamId: 1248130, genre: 'Simulación' },
  { name: 'Black Myth: Wukong', steamId: 2358720, genre: 'Acción' },
  { name: 'FINAL FANTASY VII REBIRTH', steamId: 2909400, genre: 'JRPG' },

  // — segunda tanda: juegos verificados presentes en MS Store AR (sept 2025+) —
  { name: 'RoboCop: Rogue City', steamId: 1681430, genre: 'Shooter' },
  { name: 'Dead Island 2', steamId: 934700, genre: 'Acción' },
  { name: 'Gotham Knights', steamId: 1496790, genre: 'Acción' },
  { name: 'Star Wars Outlaws', steamId: 2842040, genre: 'Aventura' },
  { name: 'Avatar: Frontiers of Pandora', steamId: 2840770, genre: 'Aventura' },
  { name: 'Prince of Persia: The Lost Crown', steamId: 2751000, genre: 'Plataformas' },
  { name: 'Avowed', steamId: 2457220, genre: 'RPG' },
  { name: 'Dead by Daylight', steamId: 381210, genre: 'Terror' },
  { name: 'Back 4 Blood', steamId: 924970, genre: 'Shooter' },
  { name: 'Clair Obscur: Expedition 33', steamId: 1903340, genre: 'JRPG' },
  { name: 'SIGNALIS', steamId: 1262350, genre: 'Terror' },
  { name: 'Amnesia: The Bunker', steamId: 1944430, genre: 'Terror' },
  { name: 'UNSIGHTED', steamId: 1062110, genre: 'Acción' },
  { name: 'Visage', steamId: 594330, genre: 'Terror' },
  { name: "Tom Clancy's The Division 2", steamId: 2221490, genre: 'Shooter' },
  { name: 'Planet Coaster 2', steamId: 2688950, genre: 'Simulación' },
  { name: 'Sniper Elite 5', steamId: 1029690, genre: 'Shooter' },
  { name: 'Wreckfest', steamId: 228380, genre: 'Carreras' },
  { name: 'SnowRunner', steamId: 1465360, genre: 'Simulación' },
  { name: 'Mortal Shell', steamId: 1110910, genre: 'RPG' },
  { name: 'Lords of the Fallen', steamId: 1501750, genre: 'Acción' },
  { name: 'Thymesia', steamId: 1343240, genre: 'Acción' },
  { name: 'STAR OCEAN THE DIVINE FORCE', steamId: 1776380, genre: 'JRPG' },
  { name: 'Metaphor: ReFantazio', steamId: 2679460, genre: 'JRPG' },
];
